### ISSUE TITLE
Data purge failure

### ISSUE THREAD

**Issue by jxmot** [jxmot/node-dht-udp#10]
After the purge timer expires and calls /mysql/index.js:purgedata() an exception occurs : 

```
TypeError: Cannot read property 'col' of undefined
    at Timeout.purgedata [as _onTimeout] (e:\Workspaces\IoT\ESP8266\arducam_K0061_ESP8266_KIT\repos\node-dht-udp\mysql\index.js:229:29)
    at ontimeout (timers.js:384:18)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by jxmot** [comment]
`purgedata(table, purge)` the arguments are incorrect. `table` is 0 and `purge` is undefined.

**Comment by jxmot** [comment]
__FIXED :__ Modified /mysql/index.js - 

* Fixed purge functions by correcting the arguments.
  * Added `purgetimerexpired(idx)`, called when the interval timer expires
  * `startPurgeTimer(table, purge, callme)` changed to `startPurgeTimer(idx, callme)`
  * `enablePurge(table, purge)` changed to `enablePurge(idx)`
  * the `idx` argument is either `dbcfg.TABLE_DATA_IDX` or `dbcfg.TABLE_STATUS_IDX`
  * when calling `startPurgeTimer(idx, callme)` the `callme` arg is `purgetimerexpired(idx)`
* Removed `var purgetimer = {...}` and ` var purgetimeouts = []`

__Changes are committed.__
__This issue will be closed after successful testing with configured interval and depth settings.__

**Comment by jxmot** [comment]
had 2 successful auto-purges. closing issue.
